### PR TITLE
Added support to setup build env with cmake

### PR DESCRIPTION
**Pull request by hwoarangmy**
+ updated code to compile with MSVS2013

### CODE REVIEW

**Comment by mgerhardy** [comment]
awesome stuff. will check it out asap

thanks a lot

**Comment by mgerhardy** [comment]
Applied to master in single commits.

**Comment by hwoarangmy** [comment]
@mgerhardy I've uploaded a bundle with the windows dependencies as said in the forum:
http://dl.free.fr/nUwn4l4zh

It will be available for 1 month. It would be nice to make it downloadable on the website. I've described how to use it in the forum thread:
http://ufoai.org/forum/index.php/topic,8898.msg64335.html#msg64335

If you have questions, you can ask in the forum thread

**Comment by ufoai** [comment]
hosted it here: https://sourceforge.net/projects/ufoai/files/UFO_AI%202.x/2.5/ufoai-deps.zip/download

thanks a lot

**Pull request closed without merging**
