### PR TITLE
ui lua integration: lua utility library for building ui structures

### PR DESCRIPTION
**Pull request by rxadmin**
This is a lua extension to building ui structures using lua. It allows to build a ui node tree from a hierarchical description of the nodes, comparable with ufo script. See wiki for additional details.

### CODE REVIEW

**Comment by mgerhardy** [comment]
Would be nice if you could get rid of the merge commit.

And for anyone wondering about the mentioned wiki docs: http://ufoai.org/wiki/UFO-Scripts/ui/LUA-utility-functions

**Comment by rxadmin** [comment]
Rebased PR.

**Comment by DarkRainX** [comment]
Well, I've merged this one now, thanks!

**Comment by rxadmin** [comment]
Thx. Closing PR.

**Pull request closed without merging**
